import math

default_transform = {
    "position": { "x": 0, "y": 0, "z": 0 },
    "rotation": { "x": 0, "y": 0, "z": 0 },
    "scale": { "x": 0.02, "y": 0.02, "z": 0.0 },
}

rotate_transform = {
    "position": { "x": 0, "y": 0, "z": 0 },
    "rotation": { "x": 0, "y": 0, "z": math.radians(90) },
    "scale": { "x": 0.02, "y": 0.02, "z": 0.0 },
}

move_transform = {
    "position": { "x": 0, "y": 0.25, "z": 0 },
    "rotation": { "x": 0, "y": 0, "z": 0 },
    "scale": { "x": 0.02, "y": 0.02, "z": 0.0 },
}

default_decimate = {
    "apply": True,
    "unsubdiv": 2,
    "dissolve": math.radians(2),
}

small_decimate = {
    "apply": True,
    "unsubdiv": 0,
    "dissolve": math.radians(0.8),
}

no_decimate = {
    "apply": False,
    "unsubdiv": 0,
    "dissolve": math.radians(0),
}

default_bake = {
    "apply": True,
    "resolution": 1024,
    "cage_extrusion": 0.02,
    "max_ray_distance": 0.0,
    "margin": 16,
}

no_bake = {
    "apply": False,
    "resolution": 1024,
    "cage_extrusion": 0.02,
    "max_ray_distance": 0.0,
    "margin": 16,
}


config = {
    # "S01_AR_D07_W02": {
    #     "index": 0,
    #     "highpoly_filepath": "SOFA_HP/HP_Armrest.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Armrest.fbx",
    #     "envelope": { "width": 0.25, "depth": 0.875 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CN_D08_W08": {
    #     "index": 1,
    #     "highpoly_filepath": "SOFA_HP/HP_Corner_100x100.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Corner_100x100.fbx",
    #     "envelope": { "width": 1, "depth": 1 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CN_D08_W08_N": {
    #     "index": 2,
    #     "highpoly_filepath": "SOFA_HP/HP_Corner_100x100_siedzisko.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Corner_100x100_siedzisko.fbx",
    #     "envelope": { "width": 1, "depth": 1 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CN_D09_W09": {
    #     "index": 3,
    #     "highpoly_filepath": "SOFA_HP/HP_Corner_112_5x112_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Corner_112_5x112_5.fbx",
    #     "envelope": { "width": 1.125, "depth": 1.125 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CN_D09_W09_N": {
    #     "index": 4,
    #     "highpoly_filepath": "SOFA_HP/HP_Corner_112_5x112_5_siedzisko.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Corner_112_5x112_5_siedzisko.fbx",
    #     "envelope": { "width": 1.125, "depth": 1.125 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D08_W06": {
    #     "index": 5,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_75x100.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_75x100.fbx",
    #     "envelope": { "width": 0.75, "depth": 1 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D08_W07": {
    #     "index": 6,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_87_5x100.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_87_5x100.fbx",
    #     "envelope": { "width": 0.875, "depth": 1 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D08_W08": {
    #     "index": 7,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_100x100.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_100x100.fbx",
    #     "envelope": { "width": 1, "depth": 1 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D08_W09": {
    #     "index": 8,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_112_5x100.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_112_5x100.fbx",
    #     "envelope": { "width": 1.125, "depth": 1 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D09_W06": {
    #     "index": 9,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_75x112_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_75x112_5.fbx",
    #     "envelope": { "width": 0.75, "depth": 1.125 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D09_W07": {
    #     "index": 10,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_87_5x112_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_87_5x112_5.fbx",
    #     "envelope": { "width": 0.875, "depth": 1.125 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D09_W08": {
    #     "index": 11,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_100x112_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_100x112_5.fbx",
    #     "envelope": { "width": 1, "depth": 1.125 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_ST_D09_W09": {
    #     "index": 12,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_112_5x112_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_112_5x112_5.fbx",
    #     "envelope": { "width": 1.125, "depth": 1.125 },
    #     "transform": default_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CL_D13_W07": {
    #     "index": 13,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_87_5x162_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_87_5x162_5.fbx",
    #     "envelope": { "width": 0.875, "depth": 1.625 },
    #     "transform": move_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CL_D13_W08": {
    #     "index": 14,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_100x162_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_100x162_5.fbx",
    #     "envelope": { "width": 1, "depth": 1.625 },
    #     "transform": move_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # "S01_CL_D13_W09": {
    #     "index": 15,
    #     "highpoly_filepath": "SOFA_HP/HP_Modul_112_5x162_5.fbx",
    #     "lowpoly_filepath": "SOFA_LP/LP_Modul_112_5x162_5.fbx",
    #     "envelope": { "width": 1.125, "depth": 1.625 },
    #     "transform": move_transform,
    #     "decimate": no_decimate,
    #     "bake": default_bake,
    # },
    # PART 2
    "S01_FR_D05_W06": {
        "index": 0,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_75x62_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_75x62_5.fbx",
        "envelope": { "width": 0.75, "depth": 0.625 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D05_W07": {
        "index": 1,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_87_5x62_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_87_5x62_5.fbx",
        "envelope": { "width": 0.875, "depth": 0.625 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D05_W08": {
        "index": 2,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x62_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x62_5.fbx",
        "envelope": { "width": 1, "depth": 0.625 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D05_W09": {
        "index": 3,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x62_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x62_5.fbx",
        "envelope": { "width": 1.125, "depth": 0.625 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D06_W06": {
        "index": 4,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_75x75.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_75x75.fbx",
        "envelope": { "width": 0.75, "depth": 0.75 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D06_W07": {
        "index": 5,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_87_5x75.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_87_5x75.fbx",
        "envelope": { "width": 0.875, "depth": 0.75 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D06_W08": {
        "index": 6,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x75.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x75.fbx",
        "envelope": { "width": 1, "depth": 0.75 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D06_W09": {
        "index": 7,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x75.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x75.fbx",
        "envelope": { "width": 1.125, "depth": 0.75 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D07_W07": {
        "index": 8,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_87_5x87_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_87_5x87_5.fbx",
        "envelope": { "width": 0.875, "depth": 0.875 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D07_W08": {
        "index": 9,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x87_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x87_5.fbx",
        "envelope": { "width": 1, "depth": 0.875 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D07_W09": {
        "index": 10,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x87_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x87_5.fbx",
        "envelope": { "width": 1.125, "depth": 0.875 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D08_W08": {
        "index": 11,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x100.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x100.fbx",
        "envelope": { "width": 1, "depth": 1 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D08_W09": {
        "index": 12,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x100.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x100.fbx",
        "envelope": { "width": 1.125, "depth": 1 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D09_W09": {
        "index": 13,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x112_5.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x112_5.fbx",
        "envelope": { "width": 1.125, "depth": 1.125 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D07_W09_N": {
        "index": 14,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x87_5_siedzisko.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x87_5_siedzisko.fbx",
        "envelope": { "width": 1.125, "depth": 0.875 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D06_W09_N": {
        "index": 15,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x75_siedzisko.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x75_siedzisko.fbx",
        "envelope": { "width": 1.125, "depth": 0.75 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D05_W09_N": {
        "index": 16,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_112_5x62_5_siedzisko.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_112_5x62_5_siedzisko.fbx",
        "envelope": { "width": 1.125, "depth": 0.625 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D07_W08_N": {
        "index": 17,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x87_5_siedzisko.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x87_5_siedzisko.fbx",
        "envelope": { "width": 1, "depth": 0.875 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D06_W08_N": {
        "index": 18,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x75_siedzisko.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x75_siedzisko.fbx",
        "envelope": { "width": 1, "depth": 0.75 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
    "S01_FR_D05_W08_N": {
        "index": 19,
        "highpoly_filepath": "SOFA_HP/HP_Ottoman_100x62_5_siedzisko.fbx",
        "lowpoly_filepath": "SOFA_LP/LP_Ottoman_100x62_5_siedzisko.fbx",
        "envelope": { "width": 1, "depth": 0.625 },
        "transform": default_transform,
        "decimate": no_decimate,
        "bake": default_bake,
    },
}
